import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@zeta/db";

export const dynamic = "force-dynamic";

// Simple markdown-to-plain-text for PDF generation without heavy deps
function mdToText(md: string): string {
  return md
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`(.*?)`/g, "$1")
    .replace(/^---+$/gm, "─".repeat(60))
    .replace(/^\s*[-*+]\s+/gm, "• ")
    .trim();
}

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  try {
    const dossier = await prisma.dossier.findUnique({
      where: { id },
      include: { org: { select: { name: true, country: true, website: true } } },
    });

    if (!dossier) {
      return NextResponse.json({ error: "Dossier not found" }, { status: 404 });
    }

    // Build HTML for PDF-like rendering (browser print / wkhtmltopdf compatible)
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${dossier.title}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Georgia', serif; font-size: 12pt; line-height: 1.7; color: #1a1a1a; background: white; padding: 40px 60px; max-width: 900px; margin: 0 auto; }
  .header { border-bottom: 3px solid #dc2626; padding-bottom: 20px; margin-bottom: 30px; }
  .header h1 { font-size: 22pt; color: #dc2626; margin-bottom: 6px; }
  .header .meta { font-size: 10pt; color: #666; }
  .header .org-badge { display: inline-block; background: #fef2f2; border: 1px solid #fca5a5; color: #dc2626; padding: 3px 10px; border-radius: 4px; font-size: 10pt; margin-top: 8px; }
  h2 { font-size: 15pt; color: #1e3a5f; margin: 28px 0 12px; border-left: 4px solid #dc2626; padding-left: 12px; }
  h3 { font-size: 12pt; color: #374151; margin: 18px 0 8px; }
  p { margin-bottom: 12px; }
  ul, ol { margin: 10px 0 10px 24px; }
  li { margin-bottom: 6px; }
  hr { border: none; border-top: 1px solid #e5e7eb; margin: 24px 0; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 9pt; color: #9ca3af; text-align: center; }
  .badge { display: inline-block; background: #f3f4f6; border-radius: 4px; padding: 2px 8px; font-size: 9pt; color: #374151; margin: 2px; }
  @media print { body { padding: 20px 40px; } }
  pre { white-space: pre-wrap; font-family: inherit; }
</style>
</head>
<body>
<div class="header">
  <div style="display:flex;align-items:center;gap:12px;margin-bottom:10px;">
    <div style="width:36px;height:36px;background:#dc2626;border-radius:8px;display:flex;align-items:center;justify-content:center;color:white;font-weight:bold;font-size:16pt;">C</div>
    <span style="font-size:11pt;color:#6b7280;font-family:sans-serif;">CAID — Cancer Advocacy Intelligence Database</span>
  </div>
  <h1>${dossier.title}</h1>
  <div class="meta">
    Generated: ${new Date(dossier.createdAt).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })} &nbsp;·&nbsp;
    Model: ${dossier.model} &nbsp;·&nbsp;
    Type: ${dossier.type}
  </div>
  <div class="org-badge">🏢 ${dossier.org.name}${dossier.org.country ? ` · ${dossier.org.country}` : ""}</div>
</div>

${dossier.content
  .split("\n")
  .map((line) => {
    if (line.startsWith("# ")) return `<h1>${line.slice(2)}</h1>`;
    if (line.startsWith("## ")) return `<h2>${line.slice(3)}</h2>`;
    if (line.startsWith("### ")) return `<h3>${line.slice(4)}</h3>`;
    if (line.startsWith("#### ")) return `<h4>${line.slice(5)}</h4>`;
    if (line.match(/^---+$/)) return `<hr>`;
    if (line.startsWith("- ") || line.startsWith("* ")) return `<li>${line.slice(2).replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")}</li>`;
    if (line.trim() === "") return `<br>`;
    return `<p>${line.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>").replace(/\*(.*?)\*/g, "<em>$1</em>")}</p>`;
  })
  .join("\n")}

<div class="footer">
  Generated by CAID Intelligence Platform &nbsp;·&nbsp; Confidential &nbsp;·&nbsp; ${new Date().getFullYear()}
  ${dossier.org.website ? `&nbsp;·&nbsp; <a href="${dossier.org.website}">${dossier.org.website}</a>` : ""}
</div>
</body>
</html>`;

    const filename = `caid_dossier_${dossier.org.name.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_${new Date(dossier.createdAt).toISOString().slice(0, 10)}.html`;

    return new Response(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (err) {
    console.error("[/api/caid/dossier/[id]/export] Error:", err);
    return NextResponse.json({ error: "Failed to export dossier" }, { status: 500 });
  }
}
